namespace Mnemonizer

open System
open System.Collections.Concurrent
open System.Collections.Generic
open System.IO
open System.Reflection

#if NET6_0_OR_GREATER
open System.Buffers
#endif

#if NET9_0_OR_GREATER
open System.Collections.Frozen
#endif

[<AutoOpen>]
module internal WordLists =

    let private readResource (name: string) =
        let asm = Assembly.GetExecutingAssembly()
        use stream = asm.GetManifestResourceStream(name)

        if isNull stream then
            invalidOp $"Embedded resource '{name}' not found."

        use reader = new StreamReader(stream)
        let text = reader.ReadToEnd()

        text.Split([| '\r'; '\n' |], StringSplitOptions.RemoveEmptyEntries)

    let defaultAdjectives = lazy readResource "Mnemonizer.adjectives.txt"
    let defaultNouns = lazy readResource "Mnemonizer.nouns.txt"


/// <summary>
/// Maps opaque system identifiers to human-readable, deterministic aliases in the form
/// <c>adjective-adjective-noun</c> (e.g. "bright-quick-falcon"). Designed for use in LLM tool-call
/// pipelines where raw IDs (GUIDs, database keys) waste context tokens and confuse the model.
/// </summary>
/// <remarks>
/// <para>
/// This type is thread-safe. All internal state is managed through <see cref="T:System.Collections.Concurrent.ConcurrentDictionary`2"/>
/// with lock-free operations. Multiple threads may call <see cref="GetOrAddAlias"/> and <see cref="TryGetId"/>
/// concurrently without external synchronization.
/// </para>
/// <para>
/// Aliases are generated by bit-packing the hash code of <typeparamref name="T"/> into three indices
/// (11 + 11 + 10 = 32 bits) selecting from 2048 adjectives and 1024 nouns, yielding ~2 billion unique aliases.
/// Hash collisions are resolved via linear probing.
/// </para>
/// <para>
/// <b>Aliases are ephemeral and scoped to a single instance.</b> Because they are derived from
/// <see cref="M:System.Collections.Generic.IEqualityComparer`1.GetHashCode(`0)"/>, the same identifier
/// may produce a different alias in a different process (e.g. when <c>string</c> hash randomization is enabled),
/// or even within the same process if collision resolution assigns a different slot due to insertion order.
/// Do not persist, serialize, or transmit aliases across instance boundaries.
/// </para>
/// </remarks>
/// <typeparam name="T">The type of the identifier to map.</typeparam>
[<Sealed>]
type MnemonicDictionary<'T>(adjectives: string[], nouns: string[], comparer: IEqualityComparer<'T>) =

    do
        if isNull (box comparer) then
            nullArg (nameof comparer)

        if adjectives.Length <> 2048 then
            invalidArg (nameof adjectives) "Must provide exactly 2048 adjectives."

        if nouns.Length <> 1024 then
            invalidArg (nameof nouns) "Must provide exactly 1024 nouns."

    let intToId = ConcurrentDictionary<uint32, 'T>()
    let aliasCache = ConcurrentDictionary<uint32, string>()

    let adjToIndex =
        let d = Dictionary<string, uint32>(2048, StringComparer.OrdinalIgnoreCase)

        for i in 0u .. uint32 (adjectives.Length - 1) do
            d.[adjectives.[int i]] <- i

        if d.Count <> adjectives.Length then
            invalidArg (nameof adjectives) "Adjectives must be unique (case-insensitive)."

#if NET9_0_OR_GREATER
        d.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase)
#else
        d
#endif

    let nounToIndex =
        let d = Dictionary<string, uint32>(1024, StringComparer.OrdinalIgnoreCase)

        for i in 0u .. uint32 (nouns.Length - 1) do
            d.[nouns.[int i]] <- i

        if d.Count <> nouns.Length then
            invalidArg (nameof nouns) "Nouns must be unique (case-insensitive)."

#if NET9_0_OR_GREATER
        d.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase)
#else
        d
#endif

#if NET6_0_OR_GREATER
    static let spanConcat (span: Span<char>) struct (a1: string, a2: string, n: string) =

        let mutable pos = 0
        a1.AsSpan().CopyTo(span.Slice(pos))
        pos <- pos + a1.Length
        span.[pos] <- '-'
        pos <- pos + 1
        a2.AsSpan().CopyTo(span.Slice(pos))
        pos <- pos + a2.Length
        span.[pos] <- '-'
        pos <- pos + 1
        n.AsSpan().CopyTo(span.Slice(pos))

    static let concatAction = SpanAction<char, struct (string * string * string)>(spanConcat)
#endif

    /// Converts the 32-bit integer hash into a readable alias.
    static let formatAlias (hash: uint32) struct (adjectives: string[], nouns: string[]) : string =
        let nounIdx = hash &&& 0x3FFu // Bottom 10 bits (1024)
        let adj2Idx = (hash >>> 10) &&& 0x7FFu // Next 11 bits (2048)
        let adj1Idx = (hash >>> 21) &&& 0x7FFu // Top 11 bits (2048)
        let adj1 = adjectives.[int adj1Idx]
        let adj2 = adjectives.[int adj2Idx]
        let noun = nouns.[int nounIdx]

#if NET6_0_OR_GREATER
        String.Create(adj1.Length + 1 + adj2.Length + 1 + noun.Length, struct (adj1, adj2, noun), concatAction)
#else
        String.Concat(adj1, "-", adj2, "-", noun)
#endif

    static let formatWrapper = Func<uint32, struct (string[] * string[]), string>(formatAlias)

    /// Applies a 32-bit mixer (avalanche function) to ensure that
    /// similar inputs produce vastly different outputs.
    static let mix (h: int) : uint32 =
        let h = uint32 h
        let h = h ^^^ (h >>> 16)
        let h = h * 0x85ebca6bu
        let h = h ^^^ (h >>> 13)
        let h = h * 0xc2b2ae35u
        let h = h ^^^ (h >>> 16)
        h

    let rec probe hash (id: 'T) =
        let existing = intToId.GetOrAdd(hash, id)

        if comparer.Equals(existing, id) then
#if NET6_0_OR_GREATER
            aliasCache.GetOrAdd(hash, formatWrapper, struct (adjectives, nouns))
#else
            aliasCache.GetOrAdd(hash, fun h -> formatAlias h struct (adjectives, nouns))
#endif
        else
            // Collision — a different id owns this slot. Linear probe.
            // Theoretically infinite but the process would OOM before we got anywhere near the end of the line.
            probe (hash + 1u) id

    /// <summary>
    /// Creates a mapper with custom word lists and the default equality comparer for <typeparamref name="T"/>.
    /// </summary>
    /// <param name="adjectives">An array of exactly 2048 adjectives.</param>
    /// <param name="nouns">An array of exactly 1024 nouns.</param>
    new(adjectives, nouns) = MnemonicDictionary(adjectives, nouns, EqualityComparer<'T>.Default)

    /// <summary>
    /// Creates a mapper with a custom equality comparer and the built-in word lists.
    /// </summary>
    /// <param name="comparer">The equality comparer used for identifier hashing and equality.</param>
    new(comparer) = MnemonicDictionary(defaultAdjectives.Value, defaultNouns.Value, comparer)

    /// <summary>
    /// Creates a mapper using the built-in word lists and the default equality comparer.
    /// The word lists are loaded lazily on first use and cached for all subsequent instances.
    /// </summary>
    new() = MnemonicDictionary(EqualityComparer<'T>.Default)

    /// <summary>
    /// Returns a deterministic, human-readable alias for the given identifier.
    /// If the identifier has been seen before, the same cached alias is returned with zero allocation.
    /// If the identifier is new, it is registered and a new alias is generated.
    /// </summary>
    /// <param name="id">The identifier to map.</param>
    /// <returns>A string in the form <c>adjective-adjective-noun</c>.</returns>
    member _.GetOrAddAlias(id: 'T) : string =
        let hash = mix (comparer.GetHashCode(id))
        probe hash id

    /// <summary>
    /// Resolves a previously generated alias back to the original identifier.
    /// On .NET 9+, this operation is zero-allocation using <c>ReadOnlySpan&lt;char&gt;</c> parsing
    /// and <c>FrozenDictionary</c> alternate lookup.
    /// </summary>
    /// <param name="alias">The alias string to look up (case-insensitive).</param>
    /// <param name="id">When this method returns <c>true</c>, contains the original identifier.</param>
    /// <returns><c>true</c> if the alias was found; otherwise <c>false</c>.</returns>
    member _.TryGetId(alias: string, id: outref<'T>) : bool =
        id <- Unchecked.defaultof<'T>

        if String.IsNullOrEmpty(alias) then
            false
        else

#if NET9_0_OR_GREATER
            // 1. Create a ReadOnlySpan to avoid allocating strings during parsing
            let span = alias.AsSpan()

            // 2. Find the hyphens
            let firstDash = span.IndexOf('-')

            if firstDash = -1 then
                false
            else

                let secondDashOffset = span.Slice(firstDash + 1).IndexOf('-')

                if secondDashOffset = -1 then
                    false
                else

                    let secondDash = firstDash + 1 + secondDashOffset

                    // 3. Slice into parts (Zero allocations)
                    let adj1Span = span.Slice(0, firstDash)
                    let adj2Span = span.Slice(firstDash + 1, secondDash - firstDash - 1)
                    let nounSpan = span.Slice(secondDash + 1)

                    // 4. Use AlternateLookup to query the string dictionary using Spans
                    let adjLookup = adjToIndex.GetAlternateLookup<ReadOnlySpan<char>>()
                    let nounLookup = nounToIndex.GetAlternateLookup<ReadOnlySpan<char>>()

                    let mutable adj1 = 0u
                    let mutable adj2 = 0u
                    let mutable noun = 0u

                    if
                        not (adjLookup.TryGetValue(adj1Span, &adj1))
                        || not (adjLookup.TryGetValue(adj2Span, &adj2))
                        || not (nounLookup.TryGetValue(nounSpan, &noun))
                    then
                        false
                    else

#else
            // Fallback for older .NET versions using string.Split (Allocates memory)
            let parts = alias.Split('-')

            if parts.Length <> 3 then
                false
            else

                let mutable adj1 = 0u
                let mutable adj2 = 0u
                let mutable noun = 0u

                if
                    not (adjToIndex.TryGetValue(parts.[0], &adj1))
                    || not (adjToIndex.TryGetValue(parts.[1], &adj2))
                    || not (nounToIndex.TryGetValue(parts.[2], &noun))
                then
                    false
                else

#endif

                    // Reconstruct the 32-bit integer
                    let uHash = (adj1 <<< 21) ||| (adj2 <<< 10) ||| noun
                    let mutable result = Unchecked.defaultof<'T>

                    if intToId.TryGetValue(uHash, &result) then
                        id <- result
                        true
                    else
                        false
