using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
#if NET6_0_OR_GREATER
using System.Buffers;
#endif
#if NET9_0_OR_GREATER
using System.Collections.Frozen;
#endif

namespace Mnemonizer
{
    internal static class WordLists
    {
        private static string[] ReadResource(string name)
        {
            var asm = Assembly.GetExecutingAssembly();
            using var stream = asm.GetManifestResourceStream(name);

            if (stream == null)
            {
                throw new InvalidOperationException($"Embedded resource '{name}' not found.");
            }

            using var reader = new StreamReader(stream);
            var text = reader.ReadToEnd();

            return text.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
        }

        public static readonly Lazy<string[]> DefaultAdjectives = new(() => ReadResource("Mnemonizer.adjectives.txt"));
        public static readonly Lazy<string[]> DefaultNouns = new(() => ReadResource("Mnemonizer.nouns.txt"));
    }

    /// <summary>
    /// Maps opaque system identifiers to human-readable, deterministic aliases in the form
    /// <c>adjective-adjective-noun</c> (e.g. "bright-quick-falcon"). Designed for use in LLM tool-call
    /// pipelines where raw IDs (GUIDs, database keys) waste context tokens and confuse the model.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This type is thread-safe. All internal state is managed through <see cref="T:System.Collections.Concurrent.ConcurrentDictionary`2"/>
    /// with lock-free operations. Multiple threads may call <see cref="GetOrAddAlias"/> and <see cref="TryGetId"/>
    /// concurrently without external synchronization.
    /// </para>
    /// <para>
    /// Aliases are generated by bit-packing the hash code of <typeparamref name="T"/> into three indices
    /// (11 + 11 + 10 = 32 bits) selecting from 2048 adjectives and 1024 nouns, yielding ~4 billion unique aliases.
    /// Hash collisions are resolved via linear probing.
    /// </para>
    /// <para>
    /// <b>Aliases are ephemeral and scoped to a single instance.</b> Because they are derived from
    /// <see cref="M:System.Collections.Generic.IEqualityComparer`1.GetHashCode(`0)"/>, the same identifier
    /// may produce a different alias in a different process (e.g. when <c>string</c> hash randomization is enabled),
    /// or even within the same process if collision resolution assigns a different slot due to insertion order.
    /// Do not persist, serialize, or transmit aliases across instance boundaries.
    /// </para>
    /// </remarks>
    /// <typeparam name="T">The type of the identifier to map.</typeparam>
    public sealed class MnemonicDictionary<T>
    {
        private readonly string[] _adjectives;
        private readonly string[] _nouns;
        private readonly IEqualityComparer<T> _comparer;

        private readonly ConcurrentDictionary<uint, T> _intToId = new();
        private readonly ConcurrentDictionary<uint, string> _aliasCache = new();

#if NET9_0_OR_GREATER
        private readonly FrozenDictionary<string, uint> _adjToIndex;
        private readonly FrozenDictionary<string, uint> _nounToIndex;
#else
        private readonly Dictionary<string, uint> _adjToIndex;
        private readonly Dictionary<string, uint> _nounToIndex;
#endif

        /// <summary>
        /// Initializes a new instance of <see cref="MnemonicDictionary{T}"/> with the specified word lists and comparer.
        /// </summary>
        /// <param name="adjectives">A list of 2048 unique adjectives to use.</param>
        /// <param name="nouns">A list of 1024 unique nouns to use.</param>
        /// <param name="comparer">The comparer to use for the identifiers.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="comparer"/> is null.</exception>
        /// <exception cref="ArgumentException">Thrown if the word lists do not have the correct number of elements or contain duplicates.</exception>
        public MnemonicDictionary(string[] adjectives, string[] nouns, IEqualityComparer<T> comparer)
        {
            if (comparer == null) throw new ArgumentNullException(nameof(comparer));
            if (adjectives.Length != 2048) throw new ArgumentException("Must provide exactly 2048 adjectives.", nameof(adjectives));
            if (nouns.Length != 1024) throw new ArgumentException("Must provide exactly 1024 nouns.", nameof(nouns));

            _adjectives = adjectives;
            _nouns = nouns;
            _comparer = comparer;

            var adjDict = new Dictionary<string, uint>(2048, StringComparer.OrdinalIgnoreCase);
            for (uint i = 0; i < (uint)adjectives.Length; i++)
            {
                adjDict[adjectives[i]] = i;
            }
            if (adjDict.Count != adjectives.Length)
            {
                throw new ArgumentException("Adjectives must be unique (case-insensitive).", nameof(adjectives));
            }

            var nounDict = new Dictionary<string, uint>(1024, StringComparer.OrdinalIgnoreCase);
            for (uint i = 0; i < (uint)nouns.Length; i++)
            {
                nounDict[nouns[i]] = i;
            }
            if (nounDict.Count != nouns.Length)
            {
                throw new ArgumentException("Nouns must be unique (case-insensitive).", nameof(nouns));
            }

#if NET9_0_OR_GREATER
            _adjToIndex = adjDict.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);
            _nounToIndex = nounDict.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);
#else
            _adjToIndex = adjDict;
            _nounToIndex = nounDict;
#endif
        }

        /// <summary>
        /// Initializes a new instance of <see cref="MnemonicDictionary{T}"/> with the specified word lists and the default comparer.
        /// </summary>
        /// <param name="adjectives">A list of 2048 unique adjectives to use.</param>
        /// <param name="nouns">A list of 1024 unique nouns to use.</param>
        /// <exception cref="ArgumentException">Thrown if the word lists do not have the correct number of elements or contain duplicates.</exception>
        public MnemonicDictionary(string[] adjectives, string[] nouns) 
            : this(adjectives, nouns, EqualityComparer<T>.Default) { }


        /// <summary>
        /// Initializes a new instance of <see cref="MnemonicDictionary{T}"/> with the specified comparer.
        /// </summary>
        /// <param name="comparer">The comparer to use for the identifiers.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="comparer"/> is null.</exception>
        public MnemonicDictionary(IEqualityComparer<T> comparer) 
            : this(WordLists.DefaultAdjectives.Value, WordLists.DefaultNouns.Value, comparer) { }


        /// <summary>
        /// Initializes a new instance of <see cref="MnemonicDictionary{T}"/> with the default word lists and comparer.
        /// </summary>
        public MnemonicDictionary() 
            : this(EqualityComparer<T>.Default) { }

#if NET6_0_OR_GREATER
        private readonly struct ConcatData
        {
            public readonly string A1;
            public readonly string A2;
            public readonly string N;

            public ConcatData(string a1, string a2, string n)
            {
                A1 = a1;
                A2 = a2;
                N = n;
            }
        }

        private static void SpanConcat(Span<char> span, ConcatData data)
        {
            int pos = 0;
            data.A1.AsSpan().CopyTo(span.Slice(pos));
            pos += data.A1.Length;
            span[pos++] = '-';
            data.A2.AsSpan().CopyTo(span.Slice(pos));
            pos += data.A2.Length;
            span[pos++] = '-';
            data.N.AsSpan().CopyTo(span.Slice(pos));
        }

        private static readonly SpanAction<char, ConcatData> ConcatAction = SpanConcat;
#endif

        private static string FormatAlias(uint hash, string[] adjectives, string[] nouns)
        {
            uint nounIdx = hash & 0x3FFu; // Bottom 10 bits (1024)
            uint adj2Idx = (hash >> 10) & 0x7FFu; // Next 11 bits (2048)
            uint adj1Idx = (hash >> 21) & 0x7FFu; // Top 11 bits (2048)
            string adj1 = adjectives[adj1Idx];
            string adj2 = adjectives[adj2Idx];
            string noun = nouns[nounIdx];

#if NET6_0_OR_GREATER
            return string.Create(adj1.Length + 1 + adj2.Length + 1 + noun.Length, new ConcatData(adj1, adj2, noun), ConcatAction);
#else
            return string.Concat(adj1, "-", adj2, "-", noun);
#endif
        }

        private static uint Mix(int hash)
        {
            uint h = (uint)hash;
            h ^= h >> 16;
            h *= 0x85ebca6bu;
            h ^= h >> 13;
            h *= 0xc2b2ae35u;
            h ^= h >> 16;
            return h;
        }

        private string Probe(uint hash, T id)
        {
            while (true)
            {
                T existing = _intToId.GetOrAdd(hash, id);

                if (_comparer.Equals(existing, id))
                {
#if NET6_0_OR_GREATER
                    // Utilizing closure-free factory in .NET 6+
                    return _aliasCache.GetOrAdd(hash, static (h, state) => FormatAlias(h, state.adjectives, state.nouns), (adjectives: _adjectives, nouns: _nouns));
#else
                    return _aliasCache.GetOrAdd(hash, h => FormatAlias(h, _adjectives, _nouns));
#endif
                }

                // Collision — a different id owns this slot. Linear probe.
                hash++;
            }
        }

        /// <summary>
        /// Returns the alias for the given identifier, adding it to the dictionary if not already present.
        /// </summary>
        /// <param name="id">The identifier for which to get or add an alias.</param>
        /// <returns>The alias associated with the given identifier.</returns>
        public string GetOrAddAlias(T id)
        {
            uint hash = Mix(_comparer.GetHashCode(id!));
            return Probe(hash, id);
        }

        /// <summary>
        /// Tries to get the identifier associated with the given alias. Returns false if the alias is not found or invalid.
        /// </summary>
        /// <param name="alias">The alias for which to get the identifier.</param>
        /// <param name="id">When this method returns, contains the identifier associated with the alias, if found; otherwise, the default value for the type.</param>
        /// <returns>true if the alias was found and the identifier was retrieved; otherwise, false.</returns>
        public bool TryGetId(string alias, out T id)
        {
            id = default!;

            if (string.IsNullOrEmpty(alias))
            {
                return false;
            }

#if NET9_0_OR_GREATER
            var span = alias.AsSpan();
            int firstDash = span.IndexOf('-');

            if (firstDash == -1)
                return false;

            int secondDashOffset = span.Slice(firstDash + 1).IndexOf('-');

            if (secondDashOffset == -1)
                return false;

            int secondDash = firstDash + 1 + secondDashOffset;

            var adj1Span = span.Slice(0, firstDash);
            var adj2Span = span.Slice(firstDash + 1, secondDash - firstDash - 1);
            var nounSpan = span.Slice(secondDash + 1);

            var adjLookup = _adjToIndex.GetAlternateLookup<ReadOnlySpan<char>>();
            var nounLookup = _nounToIndex.GetAlternateLookup<ReadOnlySpan<char>>();

            if (!adjLookup.TryGetValue(adj1Span, out uint adj1) ||
                !adjLookup.TryGetValue(adj2Span, out uint adj2) ||
                !nounLookup.TryGetValue(nounSpan, out uint noun))
            {
                return false;
            }
#else
            string[] parts = alias.Split('-');

            if (parts.Length != 3)
                return false;

            if (!_adjToIndex.TryGetValue(parts[0], out uint adj1) ||
                !_adjToIndex.TryGetValue(parts[1], out uint adj2) ||
                !_nounToIndex.TryGetValue(parts[2], out uint noun))
            {
                return false;
            }
#endif

            uint uHash = (adj1 << 21) | (adj2 << 10) | noun;

            if (_intToId.TryGetValue(uHash, out T? result))
            {
                id = result;
                return true;
            }

            return false;
        }
    }
}